services:
  guildsaber-env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    environment:
      ASPIRE_DASHBOARD_FORWARDEDHEADERS_ENABLED: "true"
    ports:
      - "3080:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "guildsaber.apphost-edbb947576-postgres-data"
        read_only: false
    networks:
      - "aspire"
  migrator:
    image: "${MIGRATOR_IMAGE}"
    pull_policy: always
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_ENVIRONMENT: ""
      ConnectionStrings__server-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=server-db"
      SERVER_DB_HOST: "postgres"
      SERVER_DB_PORT: "5432"
      SERVER_DB_USERNAME: "postgres"
      SERVER_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      SERVER_DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/server-db"
      SERVER_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/server-db"
      SERVER_DB_DATABASENAME: "server-db"
      ConnectionStrings__discordbot-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=discordbot-db"
      DISCORDBOT_DB_HOST: "postgres"
      DISCORDBOT_DB_PORT: "5432"
      DISCORDBOT_DB_USERNAME: "postgres"
      DISCORDBOT_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DISCORDBOT_DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/discordbot-db"
      DISCORDBOT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/discordbot-db"
      DISCORDBOT_DB_DATABASENAME: "discordbot-db"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://guildsaber-env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "migrator"
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    pull_policy: always
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "5042"
      ASPNETCORE_ENVIRONMENT: ""
      AuthSettings:ApiKey:Key: "${API_KEY}"
      ConnectionStrings__server-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=server-db"
      SERVER_DB_HOST: "postgres"
      SERVER_DB_PORT: "5432"
      SERVER_DB_USERNAME: "postgres"
      SERVER_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      SERVER_DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/server-db"
      SERVER_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/server-db"
      SERVER_DB_DATABASENAME: "server-db"
      services__beatleader-api__default__0: "https://api.beatleader.com/"
      beatleader_api: "https://api.beatleader.com/"
      services__beatsaver-api__default__0: "https://api.beatsaver.com/"
      beatsaver_api: "https://api.beatsaver.com/"
      services__scoresaber-api__default__0: "https://scoresaber.com/"
      scoresaber_api: "https://scoresaber.com/"
      services__beatleader-socket__default__0: "wss://sockets.api.beatleader.com/"
      beatleader_socket: "wss://sockets.api.beatleader.com/"
      AuthSettings:Manager:SteamIds:0: "${AUTHSETTINGS_MANAGER_STEAMIDS_0}"
      AuthSettings:Manager:SteamIds:1: "${AUTHSETTINGS_MANAGER_STEAMIDS_1}"
      AuthSettings:Session:ExpireAfter: "${AUTHSETTINGS_SESSION_EXPIREAFTER}"
      AuthSettings:Session:MaxSessionCount: "${AUTHSETTINGS_SESSION_MAXSESSIONCOUNT}"
      AuthSettings:Jwt:Issuer: "${AUTHSETTINGS_JWT_ISSUER}"
      AuthSettings:Jwt:Audience: "${AUTHSETTINGS_JWT_AUDIENCE}"
      AuthSettings:Jwt:Secret: "${AUTHSETTINGS_JWT_SECRET}"
      AuthSettings:BeatLeader:ClientId: "${AUTHSETTINGS_BEATLEADER_CLIENTID}"
      AuthSettings:BeatLeader:ClientSecret: "${AUTHSETTINGS_BEATLEADER_CLIENTSECRET}"
      AuthSettings:Discord:ClientId: "${AUTHSETTINGS_DISCORD_CLIENTID}"
      AuthSettings:Discord:ClientSecret: "${AUTHSETTINGS_DISCORD_CLIENTSECRET}"
      AuthSettings:Redirect:AllowedOriginUrls:0: "${AUTHSETTINGS_REDIRECT_ALLOWEDORIGINURLS_0}"
      AuthSettings:Redirect:AllowedOriginUrls:1: "${AUTHSETTINGS_REDIRECT_ALLOWEDORIGINURLS_1}"
      GuildSettings:Creation:RequiredSubscriptionTier: "${GUILDSETTINGS_CREATION_REQUIREDSUBSCRIPTIONTIER}"
      GuildSettings:Creation:MaxGuildCountPerUser: "${GUILDSETTINGS_CREATION_MAXGUILDCOUNTPERUSER}"
      RankedMapSettings:DefaultSettings:MaxRankedMapCount: "${RANKEDMAPSETTINGS_DEFAULTSETTINGS_MAXRANKEDMAPCOUNT}"
      RankedMapSettings:BoostSettings:MapCountBoosts:Tier1: "${RANKEDMAPSETTINGS_BOOSTSETTINGS_MAPCOUNTBOOSTS_TIER1}"
      RankedMapSettings:BoostSettings:MapCountBoosts:Tier2: "${RANKEDMAPSETTINGS_BOOSTSETTINGS_MAPCOUNTBOOSTS_TIER2}"
      RankedMapSettings:BoostSettings:MapCountBoosts:Tier3: "${RANKEDMAPSETTINGS_BOOSTSETTINGS_MAPCOUNTBOOSTS_TIER3}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://guildsaber-env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "5042:5042"
    depends_on:
      migrator:
        condition: "service_completed_successfully"
    networks:
      - "aspire"
  discord-bot:
    image: "${DISCORD_BOT_IMAGE}"
    pull_policy: always
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_ENVIRONMENT: ""
      AuthSettings:ApiKey: "${API_KEY}"
      ConnectionStrings__discordbot-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=discordbot-db"
      DISCORDBOT_DB_HOST: "postgres"
      DISCORDBOT_DB_PORT: "5432"
      DISCORDBOT_DB_USERNAME: "postgres"
      DISCORDBOT_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DISCORDBOT_DB_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/discordbot-db"
      DISCORDBOT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/discordbot-db"
      DISCORDBOT_DB_DATABASENAME: "discordbot-db"
      API_HTTP: "http://api:5042"
      services__api__http__0: "http://api:5042"
      DiscordBotOptions:Id: "${DISCORDBOTOPTIONS_ID}"
      DiscordBotOptions:Name: "${DISCORDBOTOPTIONS_NAME}"
      DiscordBotOptions:Status: "${DISCORDBOTOPTIONS_STATUS}"
      DiscordBotOptions:Token: "${DISCORDBOTOPTIONS_TOKEN}"
      DiscordBotOptions:GuildId: "${DISCORDBOTOPTIONS_GUILDID}"
      EmojiSettings:WatchingYou: "${EMOJISETTINGS_WATCHINGYOU}"
      EmojiSettings:NeedConfirmation: "${EMOJISETTINGS_NEEDCONFIRMATION}"
      EmojiSettings:Trophies:Plastic: "${EMOJISETTINGS_TROPHIES_PLASTIC}"
      EmojiSettings:Trophies:Silver: "${EMOJISETTINGS_TROPHIES_SILVER}"
      EmojiSettings:Trophies:Gold: "${EMOJISETTINGS_TROPHIES_GOLD}"
      EmojiSettings:Trophies:Diamond: "${EMOJISETTINGS_TROPHIES_DIAMOND}"
      EmojiSettings:Trophies:Ruby: "${EMOJISETTINGS_TROPHIES_RUBY}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://guildsaber-env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "discord-bot"
    depends_on:
      migrator:
        condition: "service_started"
      api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  guildsaber.apphost-edbb947576-postgres-data:
    driver: "local"
